### ISSUE TITLE
Allow usage without github

### ISSUE THREAD

**Issue by danielbeardsley** [iFixit/git-scripts#109]
Currently, `finish` and `merge` both require access to github to function... it'd be nice to have a git config setting `feature.use-github` (or the inverse) so this is usable without github api access.

**Comment by marczych** [comment]
I would find `feature start` and `feature merge` useful for non-GitHub projects because of how they ensure that you start on the correct branch and merge with the correct commit message into the correct branch. A simple bash/git alias could probably do the trick, though. I vote for closing this unless you still would like to see it happen, @danielbeardsley.

**Comment by danielbeardsley** [comment]
Agreed, let's close this. *We* don't need the functionality and no one else is asking for it.
